# Description: This file contains the names of the columns in the dataset.

# Column names in the dataset (Czech)
# These columns have to be in the dataset
PATIENT_ID_NAME = "PacientId"
RECORD_ID_NAME = "HlaseniIdDtb"
ICD_CODE_NAME = "DgKod"
DATE_ESTABLISHING_DG = "DatumStanoveniDg"
CODE_ESTABLISHING_DG = "StanoveniDgKod"
PN_EXAMINATION = "PNVysetreni"
PN_EXAMINATION_POS = "PNVysetreniPozitivnich"
SENTINEL_LYMPH_NODE = "SentinelovaMizniUzlinaKod"
MORPHOLOGY_CODE = "MorfologieKlasifikaceKod"
MORPHOLOGY_GRADING = "MorfologieGradingKod"
TYPE_OF_CARE = "TypPece"
YEAR_ESTABLISHING_DG = "RokStanoveniDg"
CREATED_WITH_BATCH = "ZalozenoDavkou"
CLINICAL_STADIUM = "Stadium"
EXTEND_OF_DISEASE = "OnemocneniKod"
DISTANT_METASTASIS = "VzdalenaMetastaze"
TOPOGRAPHY_CODE = "TopografieKod"
LATERALITY_CODE = "LateralitaKod"
MEDICAL_INSTITUTE_CODE = "DiagnostikujiciZdravotnickeZarizeniKod"
T = "T"
N = "N"
M = "M"
PT = "PT"
PN = "PN"
PM = "PM"
PREDICTED_COLUMN = "vyporadani_final"

# Translations of the column names from Czech to English
PATIENT_ID_NAME_ENG = "PatientId"
RECORD_ID_NAME_ENG = "RecordId"
ICD_CODE_NAME_ENG = "ICD"
CODE_ESTABLISHING_DG_ENG = "CodeEstablishingDg"
PN_EXAMINATION_ENG = "PNExamination"
PN_EXAMINATION_POS_ENG = "PNExaminationPos"
SENTINEL_LYMPH_NODE_ENG = "SentinelLymphNode"
MORPHOLOGY_GRADING_ENG = "MorphGrading"
TYPE_OF_CARE_ENG = "TypeOfCare"
YEAR_ESTABLISHING_DG_ENG = "YearDg"
CREATED_WITH_BATCH_ENG = "CreatedWithBatch"
CLINICAL_STADIUM_ENG = "ClinicalStadium"
EXTEND_OF_DISEASE_ENG = "ExtendOfDisease"
DISTANT_METASTASIS_ENG = "DistantMetastasis"
TOPOGRAPHY_CODE_ENG = "Topography"
LATERALITY_CODE_ENG = "Laterality"
PREDICTED_COLUMN_ENG = "FinalDecision"
