# Description: This file contains the names of the columns in the dataset.

# Column names in the dataset (Czech)
# These columns have to be in the dataset
VariableName = str
ColumnName = str
REQUIRED_COLUMNS : dict[VariableName, ColumnName] = {
    "PATIENT_ID_NAME": "PacientId",
    "RECORD_ID_NAME": "HlaseniIdDtb",
    "ICD_CODE_NAME": "DgKod",
    "DATE_ESTABLISHING_DG": "DatumStanoveniDg",
    "CODE_ESTABLISHING_DG": "StanoveniDgKod",
    "PN_EXAMINATION": "PNVysetreni",
    "PN_EXAMINATION_POS": "PNVysetreniPozitivnich",
    "SENTINEL_LYMPH_NODE": "SentinelovaMizniUzlinaKod",
    "MORPHOLOGY_CODE": "MorfologieKlasifikaceKod",
    "MORPHOLOGY_GRADING": "MorfologieGradingKod",
    "TYPE_OF_CARE": "TypPece",
    "YEAR_ESTABLISHING_DG": "RokStanoveniDg",
    "CREATED_WITH_BATCH": "ZalozenoDavkou",
    "CLINICAL_STADIUM": "Stadium",
    "EXTEND_OF_DISEASE": "OnemocneniKod",
    "DISTANT_METASTASIS": "VzdalenaMetastaze",
    "TOPOGRAPHY_CODE": "TopografieKod",
    "LATERALITY_CODE": "LateralitaKod",
    "MEDICAL_INSTITUTE_CODE": "DiagnostikujiciZdravotnickeZarizeniKod",
    "T": "T",
    "N": "N",
    "M": "M",
    "PT": "PT",
    "PN": "PN",
    "PM": "PM",
    "TARGET_COLUMN": "vyporadani_final",
}

# Set variables for the column names
PATIENT_ID_NAME = REQUIRED_COLUMNS["PATIENT_ID_NAME"]
RECORD_ID_NAME = REQUIRED_COLUMNS["RECORD_ID_NAME"]
ICD_CODE_NAME = REQUIRED_COLUMNS["ICD_CODE_NAME"]
DATE_ESTABLISHING_DG = REQUIRED_COLUMNS["DATE_ESTABLISHING_DG"]
CODE_ESTABLISHING_DG = REQUIRED_COLUMNS["CODE_ESTABLISHING_DG"]
PN_EXAMINATION = REQUIRED_COLUMNS["PN_EXAMINATION"]
PN_EXAMINATION_POS = REQUIRED_COLUMNS["PN_EXAMINATION_POS"]
SENTINEL_LYMPH_NODE = REQUIRED_COLUMNS["SENTINEL_LYMPH_NODE"]
MORPHOLOGY_CODE = REQUIRED_COLUMNS["MORPHOLOGY_CODE"]
MORPHOLOGY_GRADING = REQUIRED_COLUMNS["MORPHOLOGY_GRADING"]
TYPE_OF_CARE = REQUIRED_COLUMNS["TYPE_OF_CARE"]
YEAR_ESTABLISHING_DG = REQUIRED_COLUMNS["YEAR_ESTABLISHING_DG"]
CREATED_WITH_BATCH = REQUIRED_COLUMNS["CREATED_WITH_BATCH"]
CLINICAL_STADIUM = REQUIRED_COLUMNS["CLINICAL_STADIUM"]
EXTEND_OF_DISEASE = REQUIRED_COLUMNS["EXTEND_OF_DISEASE"]
DISTANT_METASTASIS = REQUIRED_COLUMNS["DISTANT_METASTASIS"]
TOPOGRAPHY_CODE = REQUIRED_COLUMNS["TOPOGRAPHY_CODE"]
LATERALITY_CODE = REQUIRED_COLUMNS["LATERALITY_CODE"]
MEDICAL_INSTITUTE_CODE = REQUIRED_COLUMNS["MEDICAL_INSTITUTE_CODE"]
T = REQUIRED_COLUMNS["T"]
N = REQUIRED_COLUMNS["N"]
M = REQUIRED_COLUMNS["M"]
PT = REQUIRED_COLUMNS["PT"]
PN = REQUIRED_COLUMNS["PN"]
PM = REQUIRED_COLUMNS["PM"]
TARGET_COLUMN = REQUIRED_COLUMNS["TARGET_COLUMN"]

# Translations of the column names from Czech to English
PATIENT_ID_NAME_ENG = "PatientId"
RECORD_ID_NAME_ENG = "RecordId"
ICD_CODE_NAME_ENG = "ICD"
CODE_ESTABLISHING_DG_ENG = "CodeEstablishingDg"
PN_EXAMINATION_ENG = "PNExamination"
PN_EXAMINATION_POS_ENG = "PNExaminationPos"
SENTINEL_LYMPH_NODE_ENG = "SentinelLymphNode"
MORPHOLOGY_GRADING_ENG = "MorphGrading"
TYPE_OF_CARE_ENG = "TypeOfCare"
YEAR_ESTABLISHING_DG_ENG = "YearDg"
CREATED_WITH_BATCH_ENG = "CreatedWithBatch"
CLINICAL_STADIUM_ENG = "ClinicalStadium"
EXTEND_OF_DISEASE_ENG = "ExtendOfDisease"
DISTANT_METASTASIS_ENG = "DistantMetastasis"
TOPOGRAPHY_CODE_ENG = "Topography"
LATERALITY_CODE_ENG = "Laterality"
TARGET_COLUMN_ENG = "FinalDecision"
